Source/TankWar/Models/ModelBinders.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using TankWar.Engine;

namespace TankWar.Models
{
    public class PointModelBinder : IModelBinder
    {
        public object BindModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
        {
            var valueProvider = bindingContext.ValueProvider.GetValue(bindingContext.ModelName);
            if (valueProvider == null)
            {
                return new Point(0,0);
            }

            var stringValue = bindingContext.ValueProvider.GetValue(bindingContext.ModelName).AttemptedValue;
            var regExMatch = Regex.Match(stringValue, @"(\d+),(\d+)");
            
            if (regExMatch.Success)
            {
                int x = Convert.ToInt32(regExMatch.Groups[1].Value);
                int y = Convert.ToInt32(regExMatch.Groups[2].Value);
                var point = new Point(x, y);
                return point;
            }
            return new Point(0, 0);
        }

    }
}

Source/TankWar/Models/ViewPortModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TankWar.Engine;
using TankWar.Engine.Dto;

namespace TankWar.Models
{
    public class ViewPortModel
    {
        public Point ViewSize { get; set; }
    }
}

Source/TankWar/Controllers/GamepadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TankWar.Controllers
{
    public class GamepadController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Source/TankWar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TankWar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Preso()
        {
            return View();
        }

    }
}

Source/TankWar/Controllers/ViewPortController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLog;
using TankWar.Engine;
using TankWar.Engine.Dto;
using TankWar.Engine.Objects;
using TankWar.Models;

namespace TankWar.Controllers
{
    public class ViewPortController : Controller
    {
        private static readonly Logger Log = LogManager.GetCurrentClassLogger();

        public ActionResult Index()
        {
            var viewModel = new ViewPortModel();
            viewModel.ViewSize = Game.Instance.GameParameters.ViewPortSize;
            return View(viewModel);
        }

        public ActionResult Admin()
        {
            return View(Game.Instance.GameParameters);
        }

        [HttpPost]
        public ActionResult ResetGameState()
        {
            Game.Instance.Init();
            return RedirectToAction("Admin");
        }

        [HttpPost]
        public ActionResult ForceStart()
        {
            Game.Instance.Start();
            return RedirectToAction("Admin");
        }

        [HttpPost]
        public ActionResult GameOver()
        {
            Game.Instance.Stop();
            return RedirectToAction("Admin");
        }

        [HttpPost]
        public ActionResult Admin(GameParameters model)
        {
            if (ModelState.IsValid)
            {
                Game.Instance.GameParameters = model;
                Log.Info("Changed game settings: {0}", model);
                return RedirectToAction("Admin");
            }
            return View(model);
        }
    }
}

Source/TankWar/Views/Gamepad/Index.cshtml
@{
    ViewBag.Title = "Tank War Gamepad";
}

<div style="display:none" data-bind="visible:true">
    <div class="row" data-bind="visible: stateWaitingForName">
        <form class="form-horizontal">
            <input type="text" class="input-large"  placeholder="What is your name soldier?" data-bind="value:name">
            <button type="submit" class="btn" data-bind="click: setName">Sir, Yes, Sir!</button>
        </form>
    </div>

    <div class="row" data-bind="visible: stateGameInCountdown">
        <h3>Hostilities are commencing in <span data-bind="text: countdown"></span></h3>
        <img src="@Url.Content("~/Content/images/countdown.jpg")" />
    </div>

    <div data-bind="visible: stateGameInPlay">
        <div class="row">
            <div class="span2">
                <div class="row">
                    <div class="span2">
                        <div id="sliderAngle" data-bind="slider:angle"></div>        
                    </div>
                </div>
                <div class="row">
                    <div class="span2"><br />
                        Angle:<span data-bind="text: angle"></span><br />
                        Power:<span data-bind="text:power"></span>
                    </div>
                </div>
            </div>
            <div class="span2">
                <div id="sliderPower" data-bind="slider:power"></div>
            </div>
        </div>
        <div class="row">
            <div class="span4">
                <button class="btn btn-danger btn-large" data-bind="click:shoot"><i class="icon-white icon-arrow-up"></i> Fire!</button>
            </div>
        </div>
    </div>
    
    <div class="row" data-bind="visible: stateGameOver">
        <img src="@Url.Content("~/Content/images/gameover.gif")" />
    </div>
    
    <div class="row" data-bind="visible: stateWaitingForNextGame">
        <h4>You are late, the battle has already started!</h4>
        <img src="@Url.Content("~/Content/images/inProgress.jpg")" />
        <h6>Don't worry, reinforcements will be required soon</h6>
    </div>

</div>
@section Scripts {
    <script src="~/Scripts/Custom/ko.bindings.js"></script>
    <script>
        
        function gamepadViewModel() {
            var self = this;
            this.hub = $.connection.gamepadHub;
            this.name = ko.observable();
            this.power = ko.observable(0);
            this.angle = ko.observable(0);
            this.countdown = ko.observable('');
            this.playerStatus = ko.observable();
            this.gameStatus = ko.observable();
            var connected = false;

            self.stateWaitingForName = ko.computed(function() { return self.playerStatus() == 'WaitingForName'; });
            self.stateGameInCountdown = ko.computed(function() { return self.playerStatus() == 'GameInCountdown'; });
            self.stateGameInPlay = ko.computed(function() { return self.playerStatus() == 'GameInPlay'; });
            self.stateGameOver = ko.computed(function() { return self.playerStatus() == 'Dead'; });
            self.stateWaitingForNextGame = ko.computed(function() { return self.playerStatus() == 'WaitingForNextGame'; });

            this.init = function() {
                this.hub.server.ping()
                    .done(this.receivePlayerStatus)
                    .fail(this.handleError);

                connected = true;
            }

            this.sendTurretStatus = function() {
                if (connected) {
                    self.hub.server.setTurret(self.power(), self.angle())
                        .fail(self.handleError);
                }
            }

            this.receivePlayerStatus = function(status) {
                console.log('playerStatus=' + status);
                self.playerStatus(status);
            }

            this.handleError = function(error) {
                console.warn(error);
            }

            this.setName = function() {
                this.hub.server.setName(this.name())
                    .done(this.updatePlayerStatus)
                    .fail(this.handleError);
            }

            this.shoot = function() {
                this.hub.server.fire()
                    .done(function() {
                        console.log('Kapoom!');
                    }).fail(this.handleError);
            }

            this.notifyGameStatus = function(gameStatus, countdownValue) {
                console.log("gameStatus=" + gameStatus + ", countdownValue=" + countdownValue);
                self.gameStatus(gameStatus);
                self.countdown(countdownValue);
            }

            this.angle.subscribe(self.sendTurretStatus);
            this.power.subscribe(self.sendTurretStatus);

        }


        $(document).ready(function() {

            var viewModel = new gamepadViewModel();
            ko.applyBindings(viewModel);

            $("#sliderPower").slider({
                orientation: "vertical",
                range: "min",
                min: 0,
                max: 100,
                value: 60
            });

            $("#sliderAngle").slider({
                range: "min",
                min: 0,
                max: 180,
                value: 90
            });

            $.connection.gamepadHub.client.notifyGameStatus = viewModel.notifyGameStatus;
            $.connection.gamepadHub.client.receivePlayerStatus = viewModel.receivePlayerStatus;

            $.connection.hub.start().done(function() {
                viewModel.init();
            });
        });
    </script>
}

Source/TankWar/Views/Home/Index.cshtml
<h1>Tank War</h1>
<p>An experiment in using SignalR &amp; Websockets.</p>
<p>Battle other players in real time, controlling your tank's turrent in the <a href="@Url.Action("Index", "Gamepad", null, this.Request.Url.Scheme)">Gamepad</a> using two sliders to control your angle and power.</p>
<p>Each change to a slider is transmitted via signalR to the GamePadHub and used to calculate the projectile motion of a shell upon firing.</p>
<p>The server runs the game loop, ticking time forward every 25ms, calculating the updated shell positions and detecting shell/tank collisions.</p>
<p>
    View the action via the <a href="@Url.Action("Index", "Viewport", null, this.Request.Url.Scheme)">Viewport</a> which is receiving the updated turret settings and shell positions on every game tick. The canvas and sprites are rendered using <a href="https://github.com/batiste/sprite.js/">sprite.js</a>.
    Try refreshing the viewport once the game starts if your tanks don't render properly.
</p>

<p>
    Tweak game parameters and control the game using the <a href="@Url.Action("Admin", "Viewport", null, this.Request.Url.Scheme)">admin page</a>.
</p>
<p>
    View the accompanying slide deck <a href="@Url.Action("Preso", "Home", null, this.Request.Url.Scheme)">here</a>
</p>

Source/TankWar/Views/Home/Preso.cshtml
@{
    ViewBag.Title = "WebSockets";
    Layout = "~/Views/Shared/_DeckJsLayout.cshtml";
}
    
    <section class="slide">
        <div>
            <h1>@ViewBag.Title</h1>
        </div>
    </section>

    <section class="slide">
        <h2>How to push updates?</h2>
        <p>HTTP works well for client fetches</p>
        <p>How to notify the client of server side events though?</p>
        <img src="@Url.Content("~/Content/slides/gmailPush.jpg")" />
    </section>

    <section class="slide">
        <h2>Polling - old school</h2>

        <pre><code>&lt;meta http-equiv="refresh" content="600"&gt; </code></pre>
    </section>

    <section class="slide">
        <h2>Polling - Web 2.0</h2>

        <pre>
<code>
setInterval(function(){
    $.ajax({ 
        url: "http://foo.com/gauges/speed"
        ,success: function(data){
            speedGauge.setValue(data.value);
        }
        ,dataType: "json"});
}, 30000);
</code>
</pre>
    </section>

    <section class="slide">
        <h2>Long Polling</h2>

        <img src="@Url.Content("~/Content/slides/longPolling.png")" />
        <p class="slide">Unthrottled server events can cause higher load than timer driven polling</p>
    </section>

    <section class="slide">
        <h2>HTTP Polling has overheads...</h2>
        <p>GET /gauges/speed</p>
        <div class="slide">
            <h3>Request Headers</h3>
            <pre><code>GET /gauges/speed HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.1.5) Gecko/20091102 Firefox/3.5.5
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-us
Accept-Encoding: gzip,deflate
Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7
Keep-Alive: 300
Connection: keep-alive
Referer: http://www.example.com/PollingStock/
Cookie: showInheritedConstant=false; showInheritedProtectedConstant=false; 
showInheritedProperty=false; showInheritedProtectedProperty=false; 
showInheritedMethod=false; showInheritedProtectedMethod=false; 
showInheritedEvent=false; showInheritedStyle=false; showInheritedEffect=false
</code>

    </pre>
        </div>
    </section>

    <section class="slide">
        <h3>Response Headers</h3>
        <pre><code>HTTP/1.x 200 OK
X-Powered-By: Servlet/2.5
Server: Sun Java System Application Server 9.1_02
Content-Type: text/html;charset=UTF-8
Content-Length: 5
Date: Tue, 28 May 2013 00:32:46 GMT
</code>

    </pre>
        <pre class="slide"><code>53.23
</code>

    </pre>
    </section>

    <section class="slide">
        <h2>In summary...</h2>
        <img src="@Url.Content("~/Content/slides/pollingKills.jpg")" />
    </section>

    <section class="slide">
        <h2>HTML 5 WebSockets</h2>
        <p class="slide">
            Once established, data frames can be sent back and forth between the client and the server. 
        </p>

        <p class="slide">
            Both text and binary frames can be sent in either direction at the same time. 
        </p>
        <div class="slide">
            <p>Client requests an upgrade:</p>

            <pre>
<code>GET ws://echo.websocket.org/?encoding=text HTTP/1.1
Origin: http://websocket.org
Cookie: __utma=99as
Connection: Upgrade
Host: echo.websocket.org
Sec-WebSocket-Key: uRovscZjNol/umbTt5uKmw==
Upgrade: websocket
Sec-WebSocket-Version: 13
</code>
</pre>
        </div>
    </section>

    <section class="slide">
        <p>If the server understands the WebSocket protocol, it responds:</p>

        <pre>
<code>HTTP/1.1 101 WebSocket Protocol Handshake
Date: Fri, 10 Feb 2012 17:38:18 GMT
Connection: Upgrade
Server: Kaazing Gateway
Upgrade: WebSocket
Access-Control-Allow-Origin: http://websocket.org
Access-Control-Allow-Credentials: true
Sec-WebSocket-Accept: rLHCkw/SKsO9GAH/ZSFhBATDKrU=
Access-Control-Allow-Headers: content-type
</code>
</pre>
        <p class="slide">
        The HTTP connection breaks down and is replaced by the WebSocket connection over the same underlying TCP/IP connection
            </p>
    </section>

    <section class="slide">
        <h2>WebSocket overhead</h2>

        <p>
            The data is framed with two bytes. Text frames use a terminator, while binary frames use a length prefix. 
        </p>
        <img src="@Url.Content("~/Content/slides/WebSocketFrame.png")" />
    </section>

    @*<section class="slide">
        <h2>Polling vs WebSocket Overhead</h2>
        <img src="@Url.Content("~/Content/slides/poll-ws-compare.gif")" />
        <ul>
            <li></li>
        </ul>
    </section>*@

    <section class="slide">
        <h2>WebSocket Usage</h2>
        <pre><code>var myWebSocket = new WebSocket("ws://www.websockets.org");</code></pre>
        <pre class="slide"><code>myWebSocket.onopen = function(evt) { 
    alert("opened..."); 
};
myWebSocket.onmessage = function(evt) { 
    alert( "Received: "  +  evt.data); 
};
myWebSocket.onclose = function(evt) { 
    alert("closed."); 
};
</code></pre>
        <pre class="slide"><code>myWebSocket.send("Hello WebSockets!");
myWebSocket.close();</code></pre>
    </section>


    <section class="slide">
        <h2>SignalR</h2>
        <blockquote cite="http://en.wikipedia.org/wiki/SignalR">
            <p>SignalR is a server-side software system designed for writing scalable Internet applications, notably web servers. Programs are written on the server side in C#, using event-driven, asynchronous I/O to minimize overhead and maximize scalability.</p>
            <p><cite>Wikipedia</cite></p>
        </blockquote>
    </section>

    <section class="slide">
        <h2>TL;DR</h2>
        <img src="@Url.Content("~/Content/slides/demoTime.jpg")" />
    </section>

    <section class="slide">
        <h2>Demo</h2>
        <img src="@Url.Content("~/Content/slides/BlockDiagram.gif")" />
    </section>

    <section class="slide">
        <h2>Choose your side</h2>
        <table>
            <tr>
                <td>
                    <img width="300" src="@Url.Content("~/Content/slides/choice1.jpg")" /></td>
                <td>
                    @Templates.SlideQRCode(Url.Action("Index", "Gamepad", null, this.Request.Url.Scheme))
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <hr />
                </td>
            </tr>
            <tr>
                <td>
                    <img width="300" src="@Url.Content("~/Content/slides/choice2.gif")" /></td>
                <td>
                    @Templates.SlideQRCode(Url.Action("Index", "Viewport", null, this.Request.Url.Scheme))
                </td>
            </tr>
        </table>
    </section>

    <section class="slide">
        <h2>SignalR - Server Side</h2>
        <h5>PersistentConnection.cs</h5>
        <ul class="slide">
            <li class="slide">Lower level</li>
            <li class="slide">Must map/decode your own messages from text</li>
        </ul>
        <h5 class="slide">Hub.cs</h5>
        <ul>
            <li class="slide">Built on PersistentConnections</li>
            <li class="slide">Allows RPC between server and client (both ways)</li>
            <li class="slide">Model binding</li>
        </ul>
    </section>
    
    <section class="slide">
        <h2>SignalR - Client to Server</h2>
        <div class="slide">
            <h4>Client Send</h4>
            <pre><code>this.sendTurretStatus = function() {
    if (connected) {
        self.hub.server
            .setTurret(
                self.power()
                ,self.angle())
            .fail(self.handleError);
    }
}
</code></pre>
        </div>

        <div class="slide">
            <h5>Server Receive</h5>
            <pre><code>public class GamepadHub : Hub
{
    public void SetTurret(int power, int angle)
    {
        var player = FindPlayer();
        if (player != null)
        {
            player.Tank.Turret.Angle = angle;
            player.Tank.Turret.Power = power;
        }
    }
...</code></pre>
        </div>       
    </section>

    <section class="slide">
        <h2>SignalR - Push to Client</h2>
        <div class="slide">
            <h5>Server Push</h5>
            <pre><code>public void PushPlayerStatus(Player player)
{
    IHubContext context = GlobalHost.ConnectionManager.GetHubContext&lt;GamepadHub&gt;();

    context
        .Clients
        .Client(player.ConnectionId)
        .receivePlayerStatus(player.Status.ToString());
}
</code></pre>
        </div>
       
        <div class="slide">
            <h4>Client Receive</h4>
            <pre><code>$.connection.gamepadHub.client
    .notifyGameStatus = viewModel.notifyGameStatus;

$.connection.gamepadHub.client
    .receivePlayerStatus = viewModel.receivePlayerStatus;

$.connection.hub.start().done(function() {
    viewModel.init();
});
</code></pre>

        </div>
    </section>

    <section class="slide">
        <h2>Whats the catch?</h2>
        <img src="@Url.Content("~/Content/slides/caniuse.jpg")" />
        <p class="slide">SignalR degrades to long polling for legacy clients</p>
    </section>

    <section class="slide">
        <h2>In summary...</h2>
        <img src="@Url.Content("~/Content/slides/iDontAlways.jpg")" />
    </section>
    
    <section class="slide">
        <h2>Questions?</h2>
    </section>

    <section class="slide">
        <img src="@Url.Content("~/Content/slides/showMeTheCode.jpg")" />

    </section>
    
    <section class="slide">
        @Templates.SlideQRCode("https://github.com/neutmute/TankWar")
    </section>
              
  

Source/TankWar/Views/Shared/_DeckJsLayout.cshtml
@{
    Layout = null;
}
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=1024, user-scalable=no">

    <title>@ViewBag.Title</title>

    <!-- Required stylesheet -->
    <link rel="stylesheet" href="~/Content/DeckJs/core/deck.core.css">

    <!-- Extension CSS files go here. Remove or add as needed. -->
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/goto/deck.goto.css">
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/menu/deck.menu.css">
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/navigation/deck.navigation.css">
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/status/deck.status.css">
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/hash/deck.hash.css">
    <link rel="stylesheet" href="~/Content/DeckJs/extensions/scale/deck.scale.css">

    <!-- Style theme. More available in /themes/style/ or create your own. -->
    <link rel="stylesheet" href="~/Content/DeckJs/themes/style/web-2.0.css">

    <!-- Transition theme. More available in /themes/transition/ or create your own. -->
    <link rel="stylesheet" href="~/Content/DeckJs/themes/transition/horizontal-slide.css">

    <!-- Required Modernizr file -->
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="deck-container">
    @RenderBody()
    
      <!-- deck.navigation snippet -->
    <a href="#" class="deck-prev-link" title="Previous">&#8592;</a>
    <a href="#" class="deck-next-link" title="Next">&#8594;</a>

    <!-- deck.status snippet -->
    <p class="deck-status">
        <span class="deck-status-current"></span>
        /
	<span class="deck-status-total"></span>
    </p>

    <!-- deck.goto snippet -->
    <form action="." method="get" class="goto-form">
        <label for="goto-slide">Go to slide:</label>
        <input type="text" name="slidenum" id="goto-slide" list="goto-datalist">
        <datalist id="goto-datalist"></datalist>
        <input type="submit" value="Go">
    </form>

    <!-- deck.hash snippet -->
    <a href="." title="Permalink to this slide" class="deck-permalink">#</a>

    <!-- End extension snippets. -->


    <!-- Required JS files. -->

    @Scripts.Render("~/bundles/jquery")
    
    <!-- Extension JS files. Add or remove as needed. -->
    <script src="~/Content/DeckJs/core/deck.core.js"></script>
    <script src="~/Content/DeckJs/extensions/hash/deck.hash.js"></script>
    <script src="~/Content/DeckJs/extensions/menu/deck.menu.js"></script>
    <script src="~/Content/DeckJs/extensions/goto/deck.goto.js"></script>
    <script src="~/Content/DeckJs/extensions/status/deck.status.js"></script>
    <script src="~/Content/DeckJs/extensions/navigation/deck.navigation.js"></script>
    <script src="~/Content/DeckJs/extensions/scale/deck.scale.js"></script>

    <!-- Initialize the deck. You can put this in an external file if desired. -->
    <script>
        $(function () {
            $.deck('.slide');
        });
    </script>
</body>
</html>

Source/TankWar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/themes/base/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/favicon.ico" rel="icon" type="image/x-icon" />
     <style>
      body {
        padding-top: 10px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
</head>
<body>
  
     <div class="container">
        @RenderBody()
     </div> <!-- /container -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/signalr")
    @Scripts.Render("~/bundles/jqueryui")
    <script src="~/Scripts/jquery.ui.touch-punch.min.js" type="text/javascript"></script>
    <script src="~/Scripts/knockout-2.2.1.js" type="text/javascript"></script>
    <script src="~/signalr/hubs" type="text/javascript"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

Source/TankWar/Views/ViewPort/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}
@model TankWar.Engine.Objects.GameParameters

<h2>Admin</h2>

<fieldset>
    <legend>Game Parameters</legend>
    @using (Html.BeginForm())
    {
        @Html.EditorForModel();
        
        @Html.LabelFor(m => m.ViewPortSize)
        @Html.EditorFor(m => m.ViewPortSize)
        <br />
        <input type="submit" class="btn btn-info btn-large" value="Set Parameters"/>

    }
</fieldset>

 <fieldset>
     <legend>God Mode</legend>
      @Html.ValidationSummary()
     <div class="row">
         <div class="span3">
             <div class="span3">
             
                 @using(Html.BeginForm("ResetGameState", "ViewPort"))
                 {
                     <input type="submit" class="btn btn-danger btn-large" value="Reset Game State"/>
                 }
     
             </div>
             @using(Html.BeginForm("ForceStart", "ViewPort"))
             {
                 <input type="submit" class="btn btn-info btn-large" value="Send Countdown to zero"/>
             }
         </div>
         <div class="span3">
             
            @using(Html.BeginForm("GameOver", "ViewPort"))
            {
                <input type="submit" class="btn btn-warning btn-large" value="Game Over"/>
            }
     
         </div>
     </div>
 </fieldset>